spring.application.name=photoGen

fal.api-key=${FAL_KEY}
fal.model-id=${FAL_MODEL_ID:fal-ai/flux-pro/kontext/text-to-image}
cors.allowed.origins=${CORS_ALLOWED_ORIGINS}
fal.model-id.enhancement=${FAL_MODEL_ID_ENHANCEMENT:fal-ai/flux-pro/kontext}
